ars/urls.py
from django.urls import path
from .views import Ars

app_name = "ars"
urlpatterns = [path("", Ars.as_view(), name="ars")]

blog/urls.py
from django.urls import path

from .views import post_list, post_add, post_edit, post_delete

app_name = "blog"
urlpatterns = [
    path("", post_list, name="post_list"),
    path("add/", post_add, name="post_add"),
    path("post_edit/<int:pk>/", post_edit, name="post_edit"),
    path("post_delete/<int:pk>/", post_delete, name="post_delete"),
]

movienite/urls.py
from django.urls import path

from .views import (
    person_list,
    person_detail,
    person_edit,
    movie_list,
    movie_add,
    movie_edit,
    movie_delete,
    person_delete,
)

app_name = "movienite"
urlpatterns = [
    path("", person_list, name="person_list"),
    path("person_detail/<int:pk>/", person_detail, name="person_detail"),
    path("person_edit/<int:pk>/", person_edit, name="person_edit"),
    path("person_delete/<int:pk>", person_delete, name="person_delete"),
    path("movie_list/", movie_list, name="movie_list"),
    path("movie_add/", movie_add, name="movie_add"),
    path("movie_edit/<int:pk>/", movie_edit, name="movie_edit"),
    path("movie_delete/<int:pk>", movie_delete, name="movie_delete"),
]

prototype/urls.py
from django.urls import path
from .views import Prototype

app_name = "prototype"
urlpatterns = [path("", Prototype.as_view(), name="prototype")]

waynoc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("blog/", include("blog.urls")),
    path("ars/", include("ars.urls")),
    path("prototype", include("prototype.urls")),
    path("", include("movienite.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
]

blog/models.py
from django.db.models import Model, CharField, TextField, DateTimeField
from django.utils import timezone


class Post(Model):
    title = CharField(max_length=255)
    text = TextField()
    date = DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

movienite/models.py
from datetime import date

from django.db.models import (
    Model,
    CharField,
    IntegerField,
    DateField,
    ForeignKey,
    SET_NULL,
    ManyToManyField,
    signals,
)
from django.dispatch import receiver
from django.urls import reverse


class Person(Model):
    name = CharField(max_length=255, unique=True)
    score = IntegerField(null=True, editable=False)

    def update_score(self):
        movies_attended = self.movies_attended.all()
        try:
            self.score = movies_attended.latest().id * 2
        except Movie.DoesNotExist:
            self.delete()
            return
        self.score += movies_attended.count()
        self.score -= 100 * self.movies_picked.count()
        for movie in movies_attended:
            self.score += 100 // movie.attendees.count()
        self.save()

    def get_absolute_url(self):
        return reverse("movienite:person_detail", args=[self.id])

    class Meta:
        ordering = ["-score", "name"]

    def __str__(self):
        return self.name


class Movie(Model):
    title = CharField(max_length=255)
    date = DateField(default=date.today)
    picker = ForeignKey(
        Person, on_delete=SET_NULL, null=True, related_name="movies_picked"
    )
    attendees = ManyToManyField(Person, related_name="movies_attended")

    def delete(self, *args, **kwargs):
        attendees = list(self.attendees.all())
        retval = super().delete(*args, **kwargs)
        for attendee in attendees:
            attendee.update_score()
        return retval

    class Meta:
        ordering = ["-date"]
        get_latest_by = "date"

    def __str__(self):
        return f"{self.title}: {self.date}"


@receiver(signals.m2m_changed, sender=Movie.attendees.through)
def movie_save(instance, action, pk_set, **_):
    if action in ["post_add", "post_remove"]:
        for attendee in instance.attendees.all():
            attendee.update_score()
    if action == "post_remove":
        for pk in pk_set:
            Person.objects.get(pk=pk).update_score()

movienite/forms.py
from django import forms

from .models import Movie, Person


class MovieForm(forms.ModelForm):
    picker = forms.ModelChoiceField(Person.objects.all(), empty_label=None)
    attendees = forms.ModelMultipleChoiceField(
        Person.objects.all(), to_field_name="name"
    )

    def __init__(self, *args, **kwargs):
        self.new_attendees = set()
        super().__init__(*args, **kwargs)

    def pre_clean_attendees(self):
        attendees = self.data.getlist("attendees")
        for attendee in attendees:
            if not Person.objects.filter(name=attendee).exists():
                self.new_attendees.add(attendee)
                attendees.remove(attendee)
        self.data = self.data.copy()
        self.data.setlist("attendees", attendees)

    def full_clean(self):
        if self.is_bound:
            self.pre_clean_attendees()
        super().full_clean()

    def save(self, *args, **kwargs):
        for attendee in self.new_attendees:
            Person(name=attendee).save()
            self.cleaned_data["attendees"] |= Person.objects.filter(name=attendee)
        return super().save(*args, **kwargs)

    class Meta:
        model = Movie
        fields = ["title", "date", "picker", "attendees"]

ars/views.py
from django.shortcuts import render
from django.views import View


class Ars(View):
    template_name = "ars/ars.html"

    @classmethod
    def get(cls, request):
        return render(request, cls.template_name)

blog/views.py
from django.contrib.auth.decorators import permission_required
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from .models import Post

post_list = ListView.as_view(model=Post, ordering="-date")

post_add = permission_required("blog.add_post")(
    CreateView.as_view(
        model=Post,
        fields=["title", "date", "text"],
        success_url=reverse_lazy("blog:post_list"),
    )
)

post_edit = permission_required("blog.change_post")(
    UpdateView.as_view(
        model=Post,
        fields=["title", "date", "text"],
        success_url=reverse_lazy("blog:post_list"),
    )
)

post_delete = permission_required("blog.delete_post")(
    DeleteView.as_view(model=Post, success_url=reverse_lazy("blog:post_list"))
)

game/views.py
from django.shortcuts import render
from django.views import View


class Game(View):
    template_name = "game/game.html"

    @classmethod
    def get(cls, request):
        return render(request, cls.template_name)

movienite/views.py
from django.contrib.auth.decorators import permission_required
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView,
)

from .forms import MovieForm
from .models import Person, Movie

person_list = ListView.as_view(model=Person)
person_detail = DetailView.as_view(model=Person)
person_edit = permission_required("movienite.change_person")(
    UpdateView.as_view(model=Person, fields=["name"])
)
person_delete = permission_required("movienite.delete_person")(
    DeleteView.as_view(
        model=Person,
        success_url=reverse_lazy("movienite:person_list"),
        template_name="movienite/confirm_delete.html",
    )
)

movie_list = ListView.as_view(
    model=Movie,
    queryset=Movie.objects.prefetch_related("attendees").select_related("picker"),
)
movie_add = permission_required("movienite.add_movie")(
    CreateView.as_view(
        model=Movie,
        form_class=MovieForm,
        success_url=reverse_lazy("movienite:movie_list"),
    )
)
movie_edit = permission_required("movienite.change_movie")(
    UpdateView.as_view(
        model=Movie,
        form_class=MovieForm,
        success_url=reverse_lazy("movienite:movie_list"),
    )
)
movie_delete = permission_required("movienite.delete_movie")(
    DeleteView.as_view(
        model=Movie,
        success_url=reverse_lazy("movienite:movie_list"),
        template_name="movienite/confirm_delete.html",
    )
)

prototype/views.py
from django.shortcuts import render
from django.views import View


class Prototype(View):
    template_name = "prototype/prototype.html"

    @classmethod
    def get(cls, request):
        return render(request, cls.template_name)

ars/templates/ars/ars.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <script
            type="module"
            src="{% static '.pyscript/node_modules/@pyscript/core/dist/core.js' %}">
    </script>
    <script type="py" src="{% static 'ars/main.py' %}"></script>
{% endblock %}

{% block content %}
    <h1 id="loading">LOADING ...</h1>
    <div id="house_descriptions" hidden>
        <p id="Bjornaer">
            Magi of Bjornaer (BYORE-nayr) concern themselves primarily with beasts and
            the animalistic side of human nature. Because of this emphasis in their
            training, each Bjornaer magus can take the form of an animal, known as his
            "heartbeast." Understanding the heartbeast in particular and animals in
            general is considered more important than Hermetic magic by many in this
            House.
        </p>
        <p id="Bonisagus">
            Bonisagus (BOH-nee-SAH-goos) invented the Hermetic theory of magic, and his
            student, the maga Trianoma, masterminded the formation of the Order. House
            Bonisagus is a true lineage; all of its members can trace their heritage
            back to Bonisagus himself.
        </p>
        <p id="Criamon">
            The very secretive House is known for its obscure philosophy, its disdain
            for simple power, and its members' habit of marking their faces and bodies
            with arcane symbols. Followers of Criamon(KREE-ah-mone) are an enigmatic and
            otherworldly group of magi, generally having little interest in the politics
            of the Order.
        </p>
    </div>
    <div id="virtue_descriptions" hidden>
        <p id="Hermetic Magus">
            You are a member of the Order of Hermes.
        </p>
        <p id="The Gift">
            You have the ability to work magic.
        </p>
        <p id="Heartbeast">
            You have been initiated into the Outer Mystery of the Heartbeast, and thus
            are a member of House Bjornaer.
        </p>
        <p id="Puissant Ability">
            You are particularly adept with one Ability, and add 2 to its value whenever
            you use it. Note that you do not, in general, use an Ability when learning
            it, teaching it, or writing about it.
        </p>
        <p id="The Enigma">
            You have been initiated into the Outer Mystery of The Enigma, and thus are a
            member of House Criamon.
        </p>
        <p id="Elemental Magic">
            You have been trained in the ability to manipulate raw elemental forms
            (Ignem, Auram, Terram and Aquam), and view them as a connected whole rather
            than four separate Arts. Whenever you successfully study one of these Arts
            (that is, gain at least one experience point from study), you gain an
            additional experience point in each of the other three.
        </p>
        <p id="Flawless Magic">
            You automatically master every spell that you learn. All your spells start
            with a score of 1 in the corresponding Ability. You may choose a different
            special ability for every spell you have. Further, all experience points you
            put into Spell Mastery Abilities are doubled.
        </p>
        <p id="Flexible Formulaic Magic">
            You can vary the effects of formulaic spells to a slight degree, while still
            getting the benefits of casting known magic. You may raise or lower the
            casting level of the spell by five to raise or lower one (only) of Range,
            Duration, and Target by one step, as long as this does not violate any of
            the normal limits on formulaic magic. Casting success, fatigue loss, and
            Penetration are all calculated based on the casting level of the spell.
            You cannot manipulate Ritual magic in this way.
        </p>
        <p id="Deficient Technique">
            All totals, including Lab and Casting totals, including a particular
            Technique are halved. Study totals are not halved. Experience points
            required are based on the actual value of the Technique, before halving.
        </p>
        <p id="Careless Sorcerer">
            You are slapdash inyour use of magical power, and must roll two more botch
            dice than normal when casting spells. Note that if you would normally roll
            no botch dice, you still roll none.
        </p>
        <p id="Clumsy Magic">
            You have trouble aiming your spells accurately. Any aiming roll is subject
            to disastrous failure: an aiming roll of 0 is automatically a botch. (Aiming
            rolls do not count as mystical rolls for the purposes of gaining Warping
            Points.) You receive a -3 penalty for any rolls involving Finesse.
        </p>
        <p id="Adept Laboratory Student">
            You digest the instructions of others quite easily. You get a +6 bonus to
            Lab Totals when working from the lab texts of others, including when
            reinventing spells.
        </p>
        <p id="Affinity with Ability">
            All Study Totals for one Ability are increased by half, as are any
            experience points you put in that Ability at character creation. If you take
            this Virtue for an Ability, you may exceed the normal age-based cap during
            character generation by two points for that Ability.
        </p>
        <p id="Deft Form">
            You are particularly skilled with one Form. You suffer no penalty to the
            Casting Total casting spells in that Form when using non-standard
            voicings/gestures, including using no voice or gestures because you are in a
            non-human form. Voice Range spells still have a Range based on how loudly
            you are speaking.
        </p>
        <p id="Giant Blood">
            The blood of the ancient race of giants flows in your veins. Though you are
            not as large as your ancestors, you are up to eight feet tall and can weigh
            as much as 500 pounds. Your Size is +2, so you can take wounds in 7-point
            increments, rather than the normal 5. You also gain +1 to both Strength and
            Stamina. This bonus may raise your scores in those Characteristics as high
            as +6.
        </p>
        <p id="Ways of the Land">
            You have a deep understanding of a type of terrain, feeling more natural and
            at home there than anywhere else. You get a +3 bonus to all rolls,
            including combat, that directly involve that area and its inhabitatnts;
            mundane, magical, or faerie. In addition, you roll one fewer botch die than
            normal (which may mean you roll no botch dice) in rolls that pertain to your
            area of understanding. You are not normally molested by animals (or people)
            of the terrain, and though particularly vicious creatures may still attack
            you, at least they'll accord you proper respect.
        </p>
        <p id="Martial Block">
            You are completely unable to learn Martial Abilities, for some reason.
        </p>
        <p id="Afflicted Tongue">
            You have a speech impediment, such as a lisp, stutter, or missing teeth. You
            suffer a -2 to all rolls involving the voice. You must also roll an extra
            botch die when casting a spell using words.
        </p>
        <p id="Arthritis">
            Your joints are stiff and often painful, making almost any prolonged
            movement difficult. You are at -3 to rolls involving repetitive movement,
            sustained over time. Occasionally, the pain is so great that you are
            seriously disabled. On any movement or combat botch, one of your joints may
            "lock up," making the limb effectively useless (-6 to all rolls involving
            it) until you have a chance to rest it for a day or two.
        </p>
        <p id="Blind">
            You have little or no sight. Using missile weapons is futile, reading is
            impossible, and navigation in unknown territory is difficult to say the
            least. As a magi, your other senses mean you are less limited by this than
            other people.
        </p>
        <p id="Crippled">
            Your legs are completely useless. You cannot walk.
        </p>
        <p id="Deaf">
            You cannot hear at all. You may be able to speak, but you cannot understand
            spoken language, which makes communication difficult. You must roll an extra
            two botch dice when casting spells with a spoken component as you cannot
            hear what you are saying.
        </p>
    </div>
    <div id="spell descriptions" hidden>
        <p id="Soothe Pains of the Beast">
            This spell looks much like a ritualistic "laying on of hands" seen in many
            churches. You kneel and press your hands to the wound while reciting a quiet
            incantation. The spell cures one Light Wound suffered by the animal.
        </p>
        <p id="Image of the Beast">
            Gives you a hazy mental image of an abimal you have an Arcane Connection to.
        </p>
        <p id="Beast of Outlandish Size">
            Changes the Size of an animal by +1. This change modifies Strength by +2,
            the range for each wound level increases by one, and Quickness falls by one.
            The new beast is of huge size and looks much more impressive than its
            previous self. Townspeople may run in fear of it, and there is little doubt
            among them that it is a creature of magic.
        </p>
        <p id="Decay Fur and Hide">
            Destroys an object made of animal fur or hide, including wool and leather.
        </p>
        <p id="Disguise of the Putrid Aroma">
            The target takes no interest in you as long as you continue to concentrate,
            and do not threaten it. A carnivore treats you as if you were simply
            something it does not eat. It retains normal interest, however, in anyone
            else nearby.
        </p>
        <p id="Footsteps of Slippery Oil">
            From each of the next ten footsteps the caster of this spell takes,
            nonflammable grease spreads out, leaving a slick area 10 paces wide.
            Dexterity stress rolls are required to remain upright whenever a character
            on the oil does something more challenging than walking. A roll of 6+ is
            needed for the average maneuver, with rolls of up to 15+ needed to
            (for example) make a right turn at full speed on a smooth, greased surface.
            The duration is the length of time that the oil lasts.
        </p>
    </div>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  {% include 'partials/delete_form.html' %}
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'blog/base.css' %}">
{% endblock %}

{% block content %}
  {% include 'partials/add_form.html' %}
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block navbar %}
  {% if perms.blog.add_post %}
    <a class="nav-link navbar-brand" href="{% url 'blog:post_add' %}">+</a>
  {% endif %}
{% endblock %}

{% block content %}
  <div class="col-md-6 offset-md-3">
    {% for post in post_list %}
      <span class="h2">{{ post.title }}</span>
      {% if perms.blog.change_post %}
        <a class="close"
           href="{% url 'blog:post_delete' post.pk %}">&#10005;</a>
        <a class="close" href="{% url 'blog:post_edit' post.pk %}">&#9998;</a>
      {% endif %}
      <div class="text-muted">
        {{ post.date }}
      </div>

      {{ post.text|linebreaks }}
    {% endfor %}
  </div>
{% endblock %}

movienite/templates/movienite/base.html
{% extends 'base.html' %}

{% block navbar %}
  {% if perms.movienite.add_movie %}
    <a class="nav-link navbar-brand"
       href="{% url 'movienite:movie_add' %}">+</a>
  {% endif %}
  {% if request.resolver_match.url_name == 'movie_list' %}
    <a class="nav-link" href="{% url 'movienite:person_list' %}">People</a>
  {% else %}
    <a class="nav-link" href="{% url 'movienite:movie_list' %}">Movies</a>
  {% endif %}
{% endblock %}

movienite/templates/movienite/confirm_delete.html
{% extends 'movienite/base.html' %}

{% block content %}
  {% include 'partials/delete_form.html' %}
{% endblock %}

movienite/templates/movienite/movie_confirm_delete.html
{% extends 'movienite/base.html' %}

{% block content %}
  {% include 'partials/delete_form.html' %}
{% endblock %}

movienite/templates/movienite/movie_form.html
{% extends 'movienite/base.html' %}

{% block content %}
  {% include 'partials/add_form.html' %}
{% endblock %}

{% block footer %}
  <script>$('#id_attendees').select2({tags: true, width: '100%'});</script>
{% endblock %}

movienite/templates/movienite/movie_list.html
{% extends 'movienite/base.html' %}

{% block content %}
  {% include 'movienite/partials/movie_table.html' %}
{% endblock %}

movienite/templates/movienite/partials/movie_table.html
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Title</th><th>Date</th><th>Picker</th><th>Attendees</th><th></th>
  </tr>
  </thead>

  <tbody>
  {% for movie in movie_list %}
  <tr>
    <td>{{ movie.title }}</td>
    <td>{{ movie.date }}</td>
    <td>
      {% if movie.picker %}
        <a href="{% url 'movienite:person_detail' movie.picker.id %}">
          {{ movie.picker.name }}</a>
      {% endif %}
    </td>
    <td>
      {% for attendee in movie.attendees.all %}
        <a href="{% url 'movienite:person_detail' attendee.id %}">
          {{ attendee.name }}</a>{% if not forloop.last %},{% endif %}
      {% endfor %}
    </td>
    {% if perms.movienite.change_movie %}
      <td>
        <a class="close" href="{% url 'movienite:movie_delete' movie.pk %}">
          &#10005;</a>
        <a class="close" href="{% url 'movienite:movie_edit' movie.pk %}">
          &#9998;</a>
      </td>
    {% endif %}
  </tr>
  {% endfor %}
  </tbody>
</table>

movienite/templates/movienite/person_detail.html
{% extends 'movienite/base.html' %}

{% block content %}
  <span class="h3">{{ person.name }}</span>
  {% if perms.movienite.change_person %}
    <a class="close"
       href="{% url 'movienite:person_edit' person.pk %}">&#9998;</a>
  {% endif %}
  <h4>Score: {{ person.score }}</h4>
  {% include 'movienite/partials/movie_table.html' with movie_list=person.movies_attended.all %}
{% endblock %}

movienite/templates/movienite/person_form.html
{% extends 'movienite/base.html' %}

{% block content %}
  {% include 'partials/add_form.html' %}
{% endblock %}

movienite/templates/movienite/person_list.html
{% extends 'movienite/base.html' %}

{% block content %}
  <div class="col-md-6 offset-md-3">
    <table class="table table-striped table-hover">
      <thead>
      <tr>
        <th></th><th>Name</th><th>Score</th>
      </tr>
      </thead>

      <tbody>
      {% for person in person_list %}
        <tr>
          <td>
            {% if perms.movienite.change_person %}
              <a class="close"
                 href="{% url 'movienite:person_delete' person.pk %}"
              >&#10005;</a>
              <a class="close"
                 href="{% url 'movienite:person_edit' person.pk %}">&#9998;</a>
            {% endif %}
          </td>
          <td>
            <a href="{% url 'movienite:person_detail' person.id %}"
            >{{ person.name }}</a>
          </td>
          <td>{{ person.score }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

prototype/templates/prototype/prototype.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <script
            type="module"
            src="{% static '.pyscript/node_modules/@pyscript/core/dist/core.js' %}">
    </script>
    <script type="py" src="{% static 'prototype/main.py' %}"
            config="{% static 'prototype/pyscript.toml' %}"></script>
{% endblock %}

{% block content %}
    <h1 id="loading">LOADING ...</h1>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en-US">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Waynoc</title>

    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link
            href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css"
            rel="stylesheet">
    {% block head %}
    {% endblock %}
</head>

<body>
<nav class="navbar navbar-light navbar-expand-md bg-light fixed-top">
    <div class="container navbar-nav">
        <div>
            <a class=
                       "nav-link navbar-brand {% if request.resolver_match.app_name == 'movienite' %}active{% endif %}"
               href="{% url 'movienite:person_list' %}">Movienite</a>
            <a class=
                       "nav-link navbar-brand {% if request.resolver_match.app_name == 'blog' %}active{% endif %}"
               href="{% url 'blog:post_list' %}">Blog</a>
            <a class=
                       "nav-link navbar-brand {% if request.resolver_match.app_name == 'ars' %}active{% endif %}"
               href="{% url 'ars:ars' %}">Ars</a>
            <a class=
                       "nav-link navbar-brand {% if request.resolver_match.app_name == 'prototype' %}active{% endif %}"
               href="{% url 'prototype:prototype' %}">Prototype</a>
            {% if user.is_staff %}
                <a class="nav-link navbar-brand"
                   href="{% url 'admin:index' %}">Admin</a>
            {% endif %}
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse justify-content-end"
             id="navbarCollapse">
            {% block navbar %}
            {% endblock %}
            {% if user.is_authenticated %}
                <a class="nav-link"
                   href="{% url 'logout' %}?next={{ request.path }}">Log Out</a>
            {% elif request.resolver_match.url_name != 'login' %}
                <a class="nav-link"
                   href="{% url 'login' %}?next={{ request.path }}">Log In</a>
            {% endif %}
        </div>
    </div>
</nav>
<main role="main" class="container">
    {% block content %}
    {% endblock %}
</main>
<footer>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
            integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
            crossorigin="anonymous"></script>
    <script
            src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"
    ></script>
    {% block footer %}
    {% endblock %}
</footer>
</body>

</html>

templates/partials/add_form.html
<form class="col-md-4 offset-md-4" method="POST"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>

templates/partials/delete_form.html
<form class="col-md-4 offset-md-4" method="POST">{% csrf_token %}
    <p>
      Are you sure you want to delete "{{ object }}"?
    </p>
    <button type="submit" class="btn btn-primary">Confirm</button>
</form>

templates/partials/form.html
{% load static %}
<form class="col-md-4 col-md-offset-4" method="POST"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>